import "@/app/globals.css";

import VikuProviders from "@/components/root/providers";
import App from "@/components/root/app";

import type { Metadata } from "next";
import { CssBaseline } from "@mui/material";
import { JSX } from "react";
import { Roboto } from "next/font/google";

// ================================================================================================

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const roboto = Roboto({
    weight: ["300", "400", "500", "700"],
    subsets: ["latin"],
    display: "swap",
    variable: "--font-roboto",
});

// ------------------------------------------------------------------------------------------------

interface RootLayoutProps {
    children: React.ReactNode;
}

export default function RootLayout(props: RootLayoutProps): JSX.Element {
    const { children } = props;
    return (
        <html lang="en" className={roboto.variable} suppressHydrationWarning>
            <body>
                <VikuProviders>
                    <CssBaseline />
                    <App>{children}</App>
                </VikuProviders>
            </body>
        </html>
    );
}
