import "@/app/globals.css";

import VikuProviders from "@/components/root/viku-providers";
import VikuApp from "@/components/root/viku-app";

import type { Metadata } from "next";
import { CssBaseline } from "@mui/material";
import { JSX } from "react";
import { Roboto } from "next/font/google";

// ================================================================================================

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const roboto = Roboto({
    weight: ["300", "400", "500", "700"],
    subsets: ["latin"],
    display: "swap",
    variable: "--font-roboto",
});

// ------------------------------------------------------------------------------------------------

interface RootLayoutProps {
    /**
     * The child nodes to render within the layout.
     */
    children: React.ReactNode;
}

/**
 * The root layout for the application. Wraps all pages with global providers and styles.
 *
 * @param props See RootLayoutProps
 */
export default function RootLayout(props: RootLayoutProps): JSX.Element {
    const { children } = props;
    return (
        <html lang="en" className={roboto.variable} suppressHydrationWarning>
            <body>
                <VikuProviders>
                    <CssBaseline />
                    <VikuApp>{children}</VikuApp>
                </VikuProviders>
            </body>
        </html>
    );
}
